In [ ]:
import numpy as np
#creating arrays
arr =np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
zeros_arr = np.zeros((3,3),dtype=int)
print(zeros_arr)
ones_arr =np.ones((2,3),dtype=int)
print(ones_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [ ]:
a = np.array([1,2],[3,4]])
b = np.array(([[5,6],[7,8]))
c =np.dot(a,b)
print(c)

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (<ipython-input-9-0c2f166972dd>, line 1)

In [ ]:
a=5
b=25
print(a+b)

30


In [ ]:
data = np.loadtxt("/content/data.txt",dtype=int)
d = np.savetxt("/content/date.txt",data)
print(d)
print(data)

ValueError: could not convert string 'hi' to int64 at row 0, column 1.

In [ ]:
arange_arr=np.arange(0,100,5)
print(arange_arr)


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
import numpy as np
a = np.arange(0,100,5)
print(a)
b=np.savetxt("/content/data.txt")


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
a= np.random.rand()
print(a)
b= np.random.rand(0,2)
print(b)
a=np.random.array([[1,2],[3,4]])
b=np.array



0.8552881439621792
[]


In [ ]:
a=np.linspace(0.8,2,5)
print(a)
c=np.arange(24).reshape(3,2,4)
print(c)
d=np.array([[2,4],[4,2]])
print(d)
b=np.array([[7,4],[7,6]])
print(b)

[0.8 1.1 1.4 1.7 2. ]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[2 4]
 [4 2]]
[[7 4]
 [7 6]]


In [ ]:
form numpy import random
a=np.ones((2,3)),(dtype=int)
print(a,sum)
print(a,sum(axis=1))

SyntaxError: invalid syntax (<ipython-input-28-c167f430159c>, line 1)

In [ ]:
import numpy as np
a = np.ones((2,3),dtype=int))
print(a.sum())
print(a.sum(axis=1))
a=np.floor(np.random((2,12)))
c=np.random.random((2,12))
print(c)


SyntaxError: unmatched ')' (<ipython-input-30-b1061a27fb29>, line 2)

In [ ]:
a=np.ones((4,5),dtype=int)
print(a,cumsum())
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))




NameError: name 'cumsum' is not defined

In [ ]:

a = np.arange(30),reshape(2,3,5)
print(a)
print(np.dstack(a))

NameError: name 'reshape' is not defined

In [ ]:
a=np.lin

In [ ]:
a=np.array((2,3,4,5,6,7,8),dtype=int)
 print(np.vc(a,b)

IndentationError: unexpected indent (<ipython-input-35-c6ca80656ffb>, line 2)

In [ ]:
from sre_constants import GROUPREF
number of rows because of GROUPRE
coloum because rows group becuse coloum

In [ ]:
a=np.array((2,3,4,5,6,7)
print(np.vc(a,b)


In [ ]:
a=np.arange(2,29)
print(a)
a=np


[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28]


In [ ]:
print np.dstack(a)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (<ipython-input-39-fb663b988247>, line 1)

In [ ]:
a=4
b=3
print(a-b)

1


In [ ]:
a=5
b=5
print(a*b)


25


In [ ]:
a=6
b=7
print(a/b)

0.8571428571428571


In [ ]:
[] al = np.eye(4)
print(a1)

SyntaxError: invalid syntax (<ipython-input-11-962e0f7b89fa>, line 1)

In [ ]:

a1 = np.full((2,3),3)
print(a1)
print(a1.itemsize)

SyntaxError: invalid syntax (<ipython-input-13-62ec89bdb8b5>, line 1)

In [ ]:
x =np .array ([1, 4, 0], float)
y =np .array ([2, 2, 1], float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

NameError: name 'np' is not defined

In [ ]:
a = np.array([1, 2 ,3 ,4 ,5])
b = np.array([2,3,6,7])






NameError: name 'np' is not defined

In [ ]:
a = 8
b = 6
c = np.hypot(a,b)
print(c)

NameError: name 'np' is not defined

In [ ]:
import numpy as np
a = np.array([30, 40,  50, 60 ])
b = np.